config/routes.rb
Rails.application.routes.draw do
  get 'projects/index'

  get 'projects/show'

  get 'users/index'

  get 'users/show'

  
  root 'pages#welcome'
  get 'portfolio' => 'pages#portfolio'
  get 'resume' => 'pages#resume'
  get 'about' => 'pages#about'
  get 'contact' => 'pages#contact'end

app/models/projects.rb
class Projects < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def welcome
    end
    
    def portfolio
    end
    
    def resume
    end
    
    def about
    end
    
    def contact
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_footer.html.erb
<div class="footer"> 
    <div class="container"> 
        <ul class="social_media"> 
            <li><a class="github" href="https://github.com/LLYX">github</a>
            </li>
            <li><a class="linkedin" href="https://www.linkedin.com/in/llyx95">linkedin</a></li> 
            <li><a class="resume" href='/resume'>resume</a></li> 
        </ul> 
        <p>&copy; 2015 Leon Xu</p> 
    </div> 
</div>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Leon Xu", '#', id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Portfolio", portfolio_path %></li>
        <li><%= link_to "Resume", resume_path %></li>
        <li><%= link_to "About", about_path %></li>
        <li><%= link_to "Contact", contact_path %></li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %></title>
      <link href='https://fonts.googleapis.com/css?family=Roboto:500,100,300,700' rel='stylesheet' type='text/css'>
      <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
      <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
      <%= csrf_meta_tags %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/pages/about.html.erb
<% provide(:title, 'About') %>
<div class="main about"> 
    <div class="container"> 
        <div class="row"> 
            <div class="col-md-6 thumbnail"> 
                <img alt="Me" 
                src="https://scontent-lga1-1.xx.fbcdn.net/hphotos-xpf1/v/t1.0-9/1530437_10202897047336074_1043920935_n.jpg?oh=2004971a5feaada1f8dba0cde2817079&oe=560536CA" /> 
            </div> 
            <div class="col-md-6"> 
                <h2>About me</h2> 
                <p>I am a third year student studying Bioinformatics, Computational
                Biology, and Computer Science at the University of Toronto, 
                St. George campus.</p> 
                <p>My major interests are in the intersection of technology and
                health. I hope to help people lead better lives through my 
                creations.</p> 
            </div> 
        </div> 
    </div> 
</div>

app/views/pages/contact.html.erb
<% provide(:title, 'Contact') %>
<div class="main contact"> 
    <div class="container"> 
        <h2>Contact me</h2> 
            <div class="row"> 
                <div class="col-md-2"><a class="github" href="https://github.com/LLYX">github</a></div> 
                <div class="col-md-2"><a class="linkedin" href="https://linkedin.com/in/llyx95">linkedin</a></div> 
            </div> 
            <div class ="row">
                <div class="col-md-2"><img src="assets/email5.svg" alt="Email" height="80" width="80"></div>
                <div class="col-md-8"><p>Or contact me through my email at leon.xu@mail.utoronto.ca</p></div>
            </div>
    </div> 
</div>

app/views/pages/portfolio.html.erb
<% provide(:title, "Portfolio") %>

app/views/pages/resume.html.erb
<% provide(:title, "Resume") %>
<%= image_tag "MyCSResume.png", :id => 'resume' %>

app/views/pages/welcome.html.erb
<% provide(:title, 'Welcome') %>
<div class="home main">
    <div class="jumbotron">
        <div class="container">
            <h1>Hello. My name is <span class="highlight">Leon Xu</span></h1>
            <h2>and I want to learn through creation.</h2> 
            <%= link_to "View my work", portfolio_path, class: "btn right" %>
        </div>
    </div>
</div>